
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public abstract partial class ActionEventParams : ET.Object
    {
        public ActionEventParams() 
        {
            EndInit();
        }


        public virtual void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

