
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class ActionEventConfig : ET.Object
    {
        public ActionEventConfig(int Id, string Name, string Desc, ET.EActionEventType ActionEventType, bool IsClientOnly, ET.ActionEventParams Params) 
        {
            this.Id = Id;
            this.Name = Name;
            this.Desc = Desc;
            this.ActionEventType = ActionEventType;
            this.IsClientOnly = IsClientOnly;
            this.Params = Params;
            EndInit();
        }

        /// <summary>
        /// 事件ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 事件类型
        /// </summary>
        public readonly ET.EActionEventType ActionEventType;
        /// <summary>
        /// 仅客户端
        /// </summary>
        public readonly bool IsClientOnly;
        /// <summary>
        /// 参数(多态)
        /// </summary>
        public readonly ET.ActionEventParams Params;

        public  void ResolveRef()
        {
            Params?.ResolveRef();
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

