
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class ActionEventParams_BallSpit : ET.ActionEventParams
    {
        public ActionEventParams_BallSpit(int CostHp, int BulletHp, float Range)  : base()
        {
            this.CostHp = CostHp;
            this.BulletHp = BulletHp;
            this.Range = Range;
            EndInit();
        }

        /// <summary>
        /// 吐球消耗自身HP
        /// </summary>
        public readonly int CostHp;
        /// <summary>
        /// 吐出子弹的HP
        /// </summary>
        public readonly int BulletHp;
        /// <summary>
        /// 吐球飞行距离
        /// </summary>
        public readonly float Range;

        public override void ResolveRef()
        {
            base.ResolveRef();
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

