
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class BallConfig : ET.Object
    {
        public BallConfig(int Id, float RadiusCoef, float BaseSpeed, float SpeedCoef, float MinSpeed, float EatRatio, int BulletDamage, int RespawnHp, int RespawnDelayMs, int MaxFoodCount, int FoodHp, float MapMin, float MapMax, int RobotCount, int RobotInitHp, int RobotThinkMs, float RobotLookahead, float RobotFleeRange, float RobotSpitRange, float RobotSpitChance) 
        {
            this.Id = Id;
            this.RadiusCoef = RadiusCoef;
            this.BaseSpeed = BaseSpeed;
            this.SpeedCoef = SpeedCoef;
            this.MinSpeed = MinSpeed;
            this.EatRatio = EatRatio;
            this.BulletDamage = BulletDamage;
            this.RespawnHp = RespawnHp;
            this.RespawnDelayMs = RespawnDelayMs;
            this.MaxFoodCount = MaxFoodCount;
            this.FoodHp = FoodHp;
            this.MapMin = MapMin;
            this.MapMax = MapMax;
            this.RobotCount = RobotCount;
            this.RobotInitHp = RobotInitHp;
            this.RobotThinkMs = RobotThinkMs;
            this.RobotLookahead = RobotLookahead;
            this.RobotFleeRange = RobotFleeRange;
            this.RobotSpitRange = RobotSpitRange;
            this.RobotSpitChance = RobotSpitChance;
            EndInit();
        }

        /// <summary>
        /// 配置ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 半径系数(R=系数*sqrt(HP))
        /// </summary>
        public readonly float RadiusCoef;
        /// <summary>
        /// 基础速度
        /// </summary>
        public readonly float BaseSpeed;
        /// <summary>
        /// 速度系数
        /// </summary>
        public readonly float SpeedCoef;
        /// <summary>
        /// 最小速度
        /// </summary>
        public readonly float MinSpeed;
        /// <summary>
        /// 吞噬比(A半径&gt;B*此值则吃)
        /// </summary>
        public readonly float EatRatio;
        /// <summary>
        /// 子弹命中扣血
        /// </summary>
        public readonly int BulletDamage;
        /// <summary>
        /// 复活HP
        /// </summary>
        public readonly int RespawnHp;
        /// <summary>
        /// 复活延迟ms
        /// </summary>
        public readonly int RespawnDelayMs;
        /// <summary>
        /// 场上食物上限
        /// </summary>
        public readonly int MaxFoodCount;
        /// <summary>
        /// 单个食物HP
        /// </summary>
        public readonly int FoodHp;
        /// <summary>
        /// 地图边界Min
        /// </summary>
        public readonly float MapMin;
        /// <summary>
        /// 地图边界Max
        /// </summary>
        public readonly float MapMax;
        /// <summary>
        /// AI机器人数
        /// </summary>
        public readonly int RobotCount;
        /// <summary>
        /// 机器人初始HP
        /// </summary>
        public readonly int RobotInitHp;
        /// <summary>
        /// 机器人思考间隔ms
        /// </summary>
        public readonly int RobotThinkMs;
        /// <summary>
        /// 机器人前瞻距离
        /// </summary>
        public readonly float RobotLookahead;
        /// <summary>
        /// 机器人逃跑距离
        /// </summary>
        public readonly float RobotFleeRange;
        /// <summary>
        /// 机器人吐球距离
        /// </summary>
        public readonly float RobotSpitRange;
        /// <summary>
        /// 机器人吐球概率
        /// </summary>
        public readonly float RobotSpitChance;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

