
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class ActionEventParams_RangeDamage : ET.ActionEventParams
    {
        public ActionEventParams_RangeDamage(int Radius)  : base()
        {
            this.Radius = Radius;
            EndInit();
        }

        /// <summary>
        /// 范围伤害半径(毫米)
        /// </summary>
        public readonly int Radius;

        public override void ResolveRef()
        {
            base.ResolveRef();
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

