
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class SkillConfig : ET.Object
    {
        public SkillConfig(int Id, int Level, int AbstractType, string Name, string Desc, int Life, int CD, System.Collections.Generic.List<int> ActionEventIds, System.Collections.Generic.List<int> ActionEventTriggerPercent) 
        {
            this.Id = Id;
            this.Level = Level;
            this.AbstractType = AbstractType;
            this.Name = Name;
            this.Desc = Desc;
            this.Life = Life;
            this.CD = CD;
            this.ActionEventIds = ActionEventIds;
            this.ActionEventTriggerPercent = ActionEventTriggerPercent;
            EndInit();
        }

        /// <summary>
        /// 技能ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 等级
        /// </summary>
        public readonly int Level;
        /// <summary>
        /// 技能类型(2主动)
        /// </summary>
        public readonly int AbstractType;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 周期ms
        /// </summary>
        public readonly int Life;
        /// <summary>
        /// CDms
        /// </summary>
        public readonly int CD;
        /// <summary>
        /// 事件ID列表
        /// </summary>
        public readonly System.Collections.Generic.List<int> ActionEventIds;
        /// <summary>
        /// 触发百分比列表
        /// </summary>
        public readonly System.Collections.Generic.List<int> ActionEventTriggerPercent;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

