
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
[ConfigGroup("Config")]
public sealed class ActionEventConfigCategoryFactory_Config : IConfigFactory
{
    public System.Type ConfigType => typeof(ActionEventConfigCategory);

    public ASingleton Create()
    {
        return new ActionEventConfigCategory(new System.Collections.Generic.Dictionary<int, ET.ActionEventConfig>()
        {
            [ 1 ] = new ET.ActionEventConfig(1, @"SpitBall", @"吐球", 8, false, new System.Collections.Generic.List<int> { }),
            [ 2 ] = new ET.ActionEventConfig(2, @"Split", @"分裂", 9, false, new System.Collections.Generic.List<int> { })
        });
    }
}
}
