
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
[ConfigGroup("Config")]
public sealed class MapConfigCategoryFactory_Config : IConfigFactory
{
    public System.Type ConfigType => typeof(MapConfigCategory);

    public ASingleton Create()
    {
        return new MapConfigCategory(new System.Collections.Generic.Dictionary<int, ET.MapConfig>()
        {
            [ 1 ] = new ET.MapConfig(1, @"GateMap", @"GateMap", ET.CopyType.Normal, @""),
            [ 2 ] = new ET.MapConfig(2, @"Map1", @"Map1", ET.CopyType.Normal, @"Map1"),
            [ 3 ] = new ET.MapConfig(3, @"Map2", @"Map2", ET.CopyType.Line, @"Map1"),
            [ 4 ] = new ET.MapConfig(4, @"Lordaeron", @"Lordaeron", ET.CopyType.Copy, @"Lordaeron"),
            [ 5 ] = new ET.MapConfig(5, @"BallBattle", @"BallBattle", ET.CopyType.Copy, @"Map1")
        });
    }
}
}
