
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
[ConfigGroup("Config")]
public sealed class UnitConfigCategoryFactory_Config : IConfigFactory
{
    public System.Type ConfigType => typeof(UnitConfigCategory);

    public ASingleton Create()
    {
        return new UnitConfigCategory(new System.Collections.Generic.Dictionary<int, ET.UnitConfig>()
        {
            [ 1001 ] = new ET.UnitConfig(1001, ET.UnitType.Player, @"Mage", @"Portrait", ET.EClassType.Mage),
            [ 1002 ] = new ET.UnitConfig(1002, ET.UnitType.Virtual, @"TrainingDummy", @"UI-ChatIcon-Battlenet", ET.EClassType.DeathKnight),
            [ 1003 ] = new ET.UnitConfig(1003, ET.UnitType.Monster, @"Boar", @"UI-ChatIcon-Battlenet", ET.EClassType.Druid),
            [ 1004 ] = new ET.UnitConfig(1004, ET.UnitType.Monster, @"Bear", @"UI-ChatIcon-Battlenet", ET.EClassType.Priest),
            [ 1005 ] = new ET.UnitConfig(1005, ET.UnitType.NPC, @"Mage", @"UI-ChatIcon-Battlenet", ET.EClassType.Warrior),
            [ 1101 ] = new ET.UnitConfig(1101, ET.UnitType.Player, @"BallPlayer", @"Portrait", ET.EClassType.Mage),
            [ 1102 ] = new ET.UnitConfig(1102, ET.UnitType.Virtual, @"BallFood", @"Portrait", ET.EClassType.Mage)
        });
    }
}
}
