//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;


namespace ET
{

public sealed partial class BuffConfig: Bright.Config.BeanBase
{
    public BuffConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);StartEvents = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); StartEvents.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);EndEvents = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); EndEvents.Add(_e0);}}
        Duration = _buf.ReadInt();
        TriggerInterval = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TriggerEvents = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TriggerEvents.Add(_e0);}}
        MaxLayer = _buf.ReadInt();
        Goup = _buf.ReadInt();
        PostInit();
    }

    public static BuffConfig DeserializeBuffConfig(ByteBuf _buf)
    {
        return new BuffConfig(_buf);
    }

    /// <summary>
    /// buffID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 备注
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 开始事件
    /// </summary>
    public System.Collections.Generic.List<int> StartEvents { get; private set; }
    /// <summary>
    /// 结束事件
    /// </summary>
    public System.Collections.Generic.List<int> EndEvents { get; private set; }
    /// <summary>
    /// 持续时间
    /// </summary>
    public int Duration { get; private set; }
    /// <summary>
    /// 触发间隔
    /// </summary>
    public int TriggerInterval { get; private set; }
    /// <summary>
    /// 触发事件id
    /// </summary>
    public System.Collections.Generic.List<int> TriggerEvents { get; private set; }
    /// <summary>
    /// 最大叠加层数
    /// </summary>
    public int MaxLayer { get; private set; }
    /// <summary>
    /// 分组
    /// </summary>
    public int Goup { get; private set; }

    public const int __ID__ = -1370631787;
    public override int GetTypeId() => __ID__;

    public  void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "StartEvents:" + Bright.Common.StringUtil.CollectionToString(StartEvents) + ","
        + "EndEvents:" + Bright.Common.StringUtil.CollectionToString(EndEvents) + ","
        + "Duration:" + Duration + ","
        + "TriggerInterval:" + TriggerInterval + ","
        + "TriggerEvents:" + Bright.Common.StringUtil.CollectionToString(TriggerEvents) + ","
        + "MaxLayer:" + MaxLayer + ","
        + "Goup:" + Goup + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}