
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
[ConfigGroup("Config")]
public sealed class ActionEventConfigCategoryFactory_Config : IConfigFactory
{
    public System.Type ConfigType => typeof(ActionEventConfigCategory);

    public ASingleton Create()
    {
        return new ActionEventConfigCategory(new System.Collections.Generic.Dictionary<int, ET.ActionEventConfig>()
        {
            [ 1 ] = new ET.ActionEventConfig(1, @"SpitBall", @"吐球", ET.EActionEventType.BallSpit, false, new ET.ActionEventParams_BallSpit(50, 30, 30f)),
            [ 2 ] = new ET.ActionEventConfig(2, @"Split", @"分裂", ET.EActionEventType.BallSplit, false, new ET.ActionEventParams_BallSplit(200, 25f))
        });
    }
}
}
