
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
/// <summary>
/// 球球大作战玩法调参(单例,固定 Id=1)
/// </summary>
[ConfigGroup("Config")]
public sealed class BallConfigCategoryFactory_Config : IConfigFactory
{
    public System.Type ConfigType => typeof(BallConfigCategory);

    public ASingleton Create()
    {
        return new BallConfigCategory(new System.Collections.Generic.Dictionary<int, ET.BallConfig>()
        {
            [ 1 ] = new ET.BallConfig(1, 0.05f, 5f, 10f, 1.5f, 1.15f, 100, 1000, 2000, 50, 50, -50f, 50f, 5, 300, 300, 20f, 12f, 10f, 0.15f)
        });
    }
}
}
