
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
[ConfigGroup("Config")]
public sealed class SkillConfigCategoryFactory_Config : IConfigFactory
{
    public System.Type ConfigType => typeof(SkillConfigCategory);

    public ASingleton Create()
    {
        return new SkillConfigCategory(new System.Collections.Generic.List<ET.SkillConfig>()
        {
            new ET.SkillConfig(1001, 1, 2, @"SpitBall", @"吐球", 200, 1000, new System.Collections.Generic.List<int> { 1 }, new System.Collections.Generic.List<int> { 0 }),
            new ET.SkillConfig(1002, 1, 2, @"Split", @"分裂", 200, 2000, new System.Collections.Generic.List<int> { 2 }, new System.Collections.Generic.List<int> { 0 })
        });
    }
}
}
