
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
[ConfigGroup("Config")]
public sealed class UnitConfigCategoryFactory_Config : IConfigFactory
{
    public System.Type ConfigType => typeof(UnitConfigCategory);

    public ASingleton Create()
    {
        return new UnitConfigCategory(new System.Collections.Generic.Dictionary<int, ET.UnitConfig>()
        {
            [ 1001 ] = new ET.UnitConfig(1001, ET.UnitType.Player, @"Mage", ET.EClassType.Mage, new System.Collections.Generic.Dictionary<NumericType, long> { [ NumericType.SpeedBase ] = 6000, [ NumericType.RadiusBase ] = 500, [ NumericType.AOIBase ] = 10000, [ NumericType.HeightBase ] = 1780, [ NumericType.WeightBase ] = 68000, [ NumericType.AI ] = 0, [ NumericType.MaxHPBase ] = 1000, [ NumericType.HP ] = 1000, [ NumericType.MaxMPBase ] = 1000, [ NumericType.MP ] = 1000, [ NumericType.Phase ] = 1, [ NumericType.X ] = 0, [ NumericType.Y ] = 25200, [ NumericType.Z ] = 10000, [ NumericType.Yaw ] = 0 }),
            [ 1002 ] = new ET.UnitConfig(1002, ET.UnitType.Virtual, @"TrainingDummy", ET.EClassType.DeathKnight, new System.Collections.Generic.Dictionary<NumericType, long> { [ NumericType.SpeedBase ] = 0, [ NumericType.RadiusBase ] = 500, [ NumericType.AOIBase ] = 0, [ NumericType.HeightBase ] = 500, [ NumericType.WeightBase ] = 30000, [ NumericType.AI ] = 300001, [ NumericType.MaxHPBase ] = 100, [ NumericType.HP ] = 100, [ NumericType.MaxMPBase ] = 100, [ NumericType.MP ] = 100, [ NumericType.Phase ] = 1 }),
            [ 1003 ] = new ET.UnitConfig(1003, ET.UnitType.Monster, @"Boar", ET.EClassType.Druid, new System.Collections.Generic.Dictionary<NumericType, long> { [ NumericType.SpeedBase ] = 0, [ NumericType.RadiusBase ] = 500, [ NumericType.AOIBase ] = 0, [ NumericType.HeightBase ] = 500, [ NumericType.WeightBase ] = 30000, [ NumericType.AI ] = 300001, [ NumericType.MaxHPBase ] = 100, [ NumericType.HP ] = 100, [ NumericType.MaxMPBase ] = 100, [ NumericType.MP ] = 100, [ NumericType.Phase ] = 1 }),
            [ 1004 ] = new ET.UnitConfig(1004, ET.UnitType.Monster, @"Bear", ET.EClassType.Priest, new System.Collections.Generic.Dictionary<NumericType, long> { [ NumericType.SpeedBase ] = 2000, [ NumericType.RadiusBase ] = 500, [ NumericType.AOIBase ] = 10000, [ NumericType.HeightBase ] = 500, [ NumericType.WeightBase ] = 30000, [ NumericType.AI ] = 300001, [ NumericType.MaxHPBase ] = 100, [ NumericType.HP ] = 100, [ NumericType.MaxMPBase ] = 100, [ NumericType.MP ] = 100, [ NumericType.Phase ] = 1 }),
            [ 1005 ] = new ET.UnitConfig(1005, ET.UnitType.NPC, @"Mage", ET.EClassType.Warrior, new System.Collections.Generic.Dictionary<NumericType, long> { [ NumericType.SpeedBase ] = 2000, [ NumericType.RadiusBase ] = 500, [ NumericType.AOIBase ] = 10000, [ NumericType.HeightBase ] = 500, [ NumericType.WeightBase ] = 30000, [ NumericType.MaxHPBase ] = 100, [ NumericType.HP ] = 100, [ NumericType.MaxMPBase ] = 100, [ NumericType.MP ] = 100, [ NumericType.Phase ] = 1 }),
            [ 1101 ] = new ET.UnitConfig(1101, ET.UnitType.Player, @"BallPlayer", ET.EClassType.Mage, new System.Collections.Generic.Dictionary<NumericType, long> { [ NumericType.SpeedBase ] = 6000, [ NumericType.RadiusBase ] = 500, [ NumericType.AOIBase ] = 10000, [ NumericType.HeightBase ] = 1780, [ NumericType.WeightBase ] = 68000, [ NumericType.AI ] = 0, [ NumericType.MaxHPBase ] = 1000, [ NumericType.HP ] = 1000, [ NumericType.MaxMPBase ] = 1000, [ NumericType.MP ] = 1000, [ NumericType.Phase ] = 1, [ NumericType.X ] = 0, [ NumericType.Y ] = 25200, [ NumericType.Z ] = 10000, [ NumericType.Yaw ] = 0 }),
            [ 1102 ] = new ET.UnitConfig(1102, ET.UnitType.Virtual, @"BallFood", ET.EClassType.Mage, new System.Collections.Generic.Dictionary<NumericType, long> { [ NumericType.SpeedBase ] = 0, [ NumericType.RadiusBase ] = 200, [ NumericType.AOIBase ] = 10000, [ NumericType.HeightBase ] = 0, [ NumericType.WeightBase ] = 0, [ NumericType.AI ] = 0, [ NumericType.MaxHPBase ] = 50, [ NumericType.HP ] = 50, [ NumericType.MaxMPBase ] = 0, [ NumericType.MP ] = 0, [ NumericType.Phase ] = 1, [ NumericType.X ] = 0, [ NumericType.Y ] = 0, [ NumericType.Z ] = 0, [ NumericType.Yaw ] = 0 })
        });
    }
}
}
