
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class ActionEventParams_Bullet : ET.ActionEventParams
    {
        public ActionEventParams_Bullet(int BulletConfigId)  : base()
        {
            this.BulletConfigId = BulletConfigId;
            EndInit();
        }

        /// <summary>
        /// 发射的子弹UnitConfig
        /// </summary>
        public readonly int BulletConfigId;

        public override void ResolveRef()
        {
            base.ResolveRef();
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

