
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class ActionEventParams_BallSplit : ET.ActionEventParams
    {
        public ActionEventParams_BallSplit(int MinHp, float Range)  : base()
        {
            this.MinHp = MinHp;
            this.Range = Range;
            EndInit();
        }

        /// <summary>
        /// 低于此HP不能分裂
        /// </summary>
        public readonly int MinHp;
        /// <summary>
        /// 分裂球冲刺距离
        /// </summary>
        public readonly float Range;

        public override void ResolveRef()
        {
            base.ResolveRef();
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

