
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{
    public sealed partial class ActionEventConfig : ET.Object
    {
        public ActionEventConfig(int Id, string Name, string Desc, int ActionEventType, bool IsClientOnly, System.Collections.Generic.List<int> Params) 
        {
            this.Id = Id;
            this.Name = Name;
            this.Desc = Desc;
            this.ActionEventType = ActionEventType;
            this.IsClientOnly = IsClientOnly;
            this.Params = Params;
            EndInit();
        }

        /// <summary>
        /// 事件ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 事件类型(8吐球 9分裂)
        /// </summary>
        public readonly int ActionEventType;
        /// <summary>
        /// 仅客户端
        /// </summary>
        public readonly bool IsClientOnly;
        /// <summary>
        /// 参数
        /// </summary>
        public readonly System.Collections.Generic.List<int> Params;

        public  void ResolveRef()
        {
            EndRef();
        }

        partial void EndInit();
        partial void EndRef();
    }

}

