
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{
/// <summary>
/// 球球大作战玩法调参(单例,固定 Id=1)
/// </summary>
[ConfigProcess(ConfigType.Code)]
public partial class BallConfigCategory : Singleton<BallConfigCategory>, IConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ET.BallConfig> _dataMap;

    public BallConfigCategory(System.Collections.Generic.Dictionary<int, ET.BallConfig> dataMap)
    {
        _dataMap = dataMap;
    }

    public System.Collections.Generic.Dictionary<int, ET.BallConfig> GetAll() => _dataMap;
    public System.Collections.Generic.IReadOnlyDictionary<int, ET.BallConfig> DataMap => _dataMap;
    public ET.BallConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ET.BallConfig Get(int key) => _dataMap[key];
    public ET.BallConfig this[int key] => _dataMap[key];

    public void ResolveRef()
    {
        foreach (var _v in _dataMap.Values)
        {
            _v.ResolveRef();
        }
        EndRef();
    }

    partial void EndRef();
}
}

