
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum EActionEventType
    {
        /// <summary>
        /// 范围伤害
        /// </summary>
        RangeDamage = 1,
        /// <summary>
        /// 子弹
        /// </summary>
        Bullet = 2,
        /// <summary>
        /// 添加buff
        /// </summary>
        AddBuff = 3,
        /// <summary>
        /// 移除buff
        /// </summary>
        RemoveBuff = 4,
        /// <summary>
        /// 隐身
        /// </summary>
        Stealth = 5,
        /// <summary>
        /// 无敌
        /// </summary>
        Invincible = 6,
        /// <summary>
        /// 改数值
        /// </summary>
        ChangeNumeric = 7,
        /// <summary>
        /// 吐球
        /// </summary>
        BallSpit = 8,
        /// <summary>
        /// 分裂
        /// </summary>
        BallSplit = 9,
        /// <summary>
        /// 播放动画
        /// </summary>
        PlayAnimation = 100,
        /// <summary>
        /// 镜头震动
        /// </summary>
        ShakeCamera = 101,
        /// <summary>
        /// 播放特效
        /// </summary>
        PlayEffect = 102,
        /// <summary>
        /// 播放音效
        /// </summary>
        PlaySound = 103,
        /// <summary>
        /// 隐藏武器
        /// </summary>
        HideWeapon = 104,
        /// <summary>
        /// 播放材质
        /// </summary>
        PlayMaterial = 105,
        /// <summary>
        /// 恢复材质
        /// </summary>
        RecoverMaterial = 106,
    }

} 

