
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{
[ConfigProcess(ConfigType.Code)]
public partial class SkillConfigCategory : Singleton<SkillConfigCategory>, IConfig
{
    private readonly System.Collections.Generic.List<ET.SkillConfig> _dataList;
    private readonly System.Collections.Generic.Dictionary<(int, int), ET.SkillConfig> _dataMapUnion;

    public SkillConfigCategory(System.Collections.Generic.List<ET.SkillConfig> dataList)
    {
        _dataList = dataList;
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), ET.SkillConfig>(_dataList.Count);
        foreach (var _v in _dataList)
        {
            _dataMapUnion.Add((_v.Id, _v.Level), _v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<ET.SkillConfig> DataList => _dataList;
    public ET.SkillConfig Get(int Id, int Level) => _dataMapUnion.TryGetValue((Id, Level), out ET.SkillConfig __v) ? __v : default;

    public void ResolveRef()
    {
        foreach (var _v in _dataList)
        {
            _v.ResolveRef();
        }
        EndRef();
    }

    partial void EndRef();
}
}

