//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{ 
    public enum EActionEventType
    {
        RangeDamage = 1,
        Bullet = 2,
        AddBuff = 3,
        RemoveBuff = 4,
        Stealth = 5,
    }

} 
