//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{ 
    public enum ESkillAbstractType
    {
        NormalAttack = 1,
        ActiveSkill = 2,
        PassiveSkill = 3,
        WeaponSkill = 4,
        MountSkill = 5,
    }

} 
