//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{ 
    public enum EUnitType
    {
        Player = 1,
        Monster = 2,
        NPC = 3,
        Bullet = 4,
        Food = 5,
    }

} 
