//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;

namespace ET
{
   
[Config]
public partial class SkillConfigCategory: ConfigSingleton<SkillConfigCategory>
{
    private readonly List<SkillConfig> _dataList;

    private Dictionary<(int, int), SkillConfig> _dataMapUnion;

    public SkillConfigCategory(ByteBuf _buf)
    {
        _dataList = new List<SkillConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SkillConfig _v;
            _v = SkillConfig.DeserializeSkillConfig(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion = new Dictionary<(int, int), SkillConfig>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.Id, _v.Level), _v);
        }
        PostInit();
    }

    public List<SkillConfig> DataList => _dataList;

    public SkillConfig Get(int Id, int Level) => _dataMapUnion.TryGetValue((Id, Level), out SkillConfig __v) ? __v : null;

    public override void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataList.TrimExcess();
    }
        
    
    public override string ConfigName()
    {
        return typeof(SkillConfig).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}